In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


# Introduction to Tensors

## Creating a tensors

In [ ]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# checking the dimensions of the tenssors
scalar.ndim

0

In [ ]:
# Get back the tensor as the python integer
scalar.item()

7

In [ ]:
# vector reprsentation

# The number of the square bracket also tell us the number of the dimesnions
vector = torch.tensor([4,5,6])


In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
# MATRIX Representaion

MATRIX = torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
MATRIX.ndim

2

In [ ]:
# Takind the element from the 0th index
MATRIX[0]

tensor([1, 2])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# 3D Matrix tensor

Tensors = torch.tensor([[[1,2,3],
                         [4,5,6],
                         [7,8,9]]])

Tensors

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
Tensors.ndim

3

In [ ]:
Tensors.shape

torch.Size([1, 3, 3])

In [ ]:
Tensors = torch.tensor(
    [
      [
        [
            [[1,2,3],
             [4,5,6],
             [7,8,9],
             [10,11,12]]
            ]
        ]
    ]
)


In [ ]:
Tensors.shape

torch.Size([1, 1, 1, 4, 3])

In [ ]:
Tensors.ndim

5

# Random Tensors

### Why random tensors?
#### Random tensors are important beacuse the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

` start with random numbers -> look at data ->update the random numbers -> look at data -> update random numbers -> for the better representaion`

In [ ]:
# Creating the random tensors

random_tensor = torch.rand(1,1,4,4)
random_tensor

tensor([[[[6.6707e-02, 2.0235e-01, 5.8477e-01, 3.8978e-01],
          [9.1053e-01, 2.4550e-01, 7.1191e-01, 4.2125e-01],
          [2.8527e-04, 4.1557e-01, 7.4619e-01, 5.4858e-01],
          [6.7583e-01, 7.9663e-01, 7.8859e-02, 3.1859e-01]]]])

In [ ]:
random_tensor.shape

torch.Size([1, 1, 4, 4])

In [ ]:
random_tensor.ndim

4

In [ ]:
# Creating the random tensors with similar to an image tensor

random_image_size_tensor = torch.rand(size=(244,244,3)) # height , width , channel (red,green,blue)
random_image_size_tensor.shape

torch.Size([244, 244, 3])

In [ ]:
random_image_size_tensor.ndim

3

In [ ]:
# Creating a tensors of all Zeros

all_zeros_tensors = torch.zeros(3,4)

In [ ]:
all_zeros_tensors , all_zeros_tensors.shape

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.Size([3, 4]))

In [ ]:
all_zeros_tensors.dtype

torch.float32

In [ ]:
# Creating a tensors with all ones
all_ones_tensor = torch.ones(3,4)
all_ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Creating a range of tensors and tensors-like

In [ ]:
# use torch.range()

one_to_ten = torch.arange(0,11,1) # start , end , step
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensors Datatypes
**Note** : Tensor datatypes is one if the 3 big errors will run into with pTorch & Deep learning


1.   Tensor not right datatype
2.   Tensor not right shape
3.   Tensors not on the right device







In [ ]:
# these three are the important paramter while creating the tensors but pytorch take care it

# here the flaot 32bit means the computer precision

float_32_tensor = torch.tensor([3,4,5,6] ,
                               dtype= torch.float32, # what datatype is the tensor (e.g float32 or float16)
                               device = None, # What device is your tensor on
                               requires_grad= False # wheather or not to track the gradients with this tensor operations
                               )
float_32_tensor


tensor([3., 4., 5., 6.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
# Multiply the tensors of the data type 16 and 32

float_16_tensor * float_32_tensor

tensor([ 9., 16., 25., 36.])

In [ ]:
# multiplying the tensor if 16/32 with zero/one tensor
float_16_tensor * all_ones_tensor[0]

tensor([3., 4., 5., 6.])

In [ ]:
# creating the int32bit tensor

int_32_tensor = torch.tensor([3,4,5,6],dtype=torch.int32)
int_32_tensor

tensor([3, 4, 5, 6], dtype=torch.int32)

In [ ]:
# multipling the 32bit fload and integer
float_32_tensor * int_32_tensor

tensor([ 9., 16., 25., 36.])

## Getting information from tensors
#### Three Common issues in building neural and deep learning models
1. Tensor not right datatype - to do get datatype from a tensor, can use `tensor.dtype `
2. Tensor not right shape - to do get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to do get device from a tensor, can use `tensor.device`

In [ ]:
# creating a some tensor and getting information out of it

some_tensor = torch.rand(3,3)
some_tensor

tensor([[0.3683, 0.9662, 0.0049],
        [0.4096, 0.3358, 0.2286],
        [0.1276, 0.6214, 0.6079]])

In [ ]:
print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

tensor([[0.3683, 0.9662, 0.0049],
        [0.4096, 0.3358, 0.2286],
        [0.1276, 0.6214, 0.6079]])
torch.float32
torch.Size([3, 3])
cpu


## Manipulating tensors (tensir Operations)

In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.
And these operations are often a wonderful dance between:

* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor of values and add number to it
tensor =  torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# subtracting a number from it
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# multiplying the tensor with the 10
tensor * 10

tensor([10, 20, 30])

#### Python also have built in function for this type of multiplication like `torch.mul()` and many other

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
# see more built in functions

torch.add(tensor,3)

tensor([4, 5, 6])

In [ ]:
torch.div(tensor,2)

tensor([0.5000, 1.0000, 1.5000])

In [ ]:
print(tensor * tensor)


tensor([1, 4, 9])


In [ ]:
print(torch.matmul(tensor,tensor))


tensor(14)


# Matrix Multiplication

one of the most important deep learning and machine learning operation(like neural networks) is matrix multiplication.

Pytorch implements matrix multiplication functionality in the `torch.matmul()` method.

The two main rules for the matrix multiplication to remember are

1. The **inner dimensions** must match:
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work

2. The resulting matrix has the shape of the outer dimensions:
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)
Note: "@" in Python is the symbol for matrix multiplication.

Resource: You can see all of the rules for matrix multiplication using torch.matmul() in the PyTorch documentation.

In [ ]:
torch.matmul(torch.rand(2,3),torch.rand(2,3))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

# instead of matmul we can also use the {@} --> but recommended way is to use the { matmul() }

tensor([[0.2457, 1.0541, 0.8178],
        [0.0881, 0.7811, 0.1962],
        [0.2126, 0.3564, 0.8412]])

In [ ]:
torch.matmul(torch.rand(10,10),torch.rand(10,10)).shape

torch.Size([10, 10])

# One of the most common error in the deep learning: Shape Errors

In [ ]:
# shapes for the matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

mul = torch.matmul(tensor_A,tensor_B) #  we can also wirte (mm) --> instead of matmul
print(mul)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### To Fix our tensor shape issues, we can manipulate the shape of ones of our tensor using a `Transpose`
A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B.T , tensor_B.T.shape

In [ ]:
tensor_B , tensor_B.shape

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 torch.Size([3, 2]))

In [ ]:
# now we will perform operation for the matrix multiplication and check is the preveious shape error still exist with the transpose method

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")

torch.matmul(tensor_A,tensor_B.T)

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])


tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

In [ ]:
torch.matmul(tensor_A.T , tensor_B)

tensor([[35, 44],
        [44, 56]])

In [ ]:
tensor_C = torch.tensor([[1,2,3,4],
                         [5,6,7,8]])

In [ ]:
torch.matmul(tensor_A , tensor_C)

tensor([[11, 14, 17, 20],
        [23, 30, 37, 44],
        [35, 46, 57, 68]])

In [ ]:
tensor_A.shape , tensor_C.shape

(torch.Size([3, 2]), torch.Size([2, 4]))

# Find the min , max, mean ,sum,etc `TENSOR AGGREGATION`

this is called aggregation beacuse we are going from the typically a large amount of values to a one element

In [ ]:
x = torch.arange(0,100,10)
print(x)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [ ]:
# Finding the minimum
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Finding the maximum
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - note: the torch.mean() requires a tensor of float32 datatype
torch.mean(x)

# so we have to change the datatype of the tensor and convert it into the tensor32 float type

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# calculating the sum of the tensor
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
# find the position in tensir that has the minimum vlaue with argmin() -> returns index position of target tensor where the minimum value occurs

torch.argmin(x) , x.argmin() # --> returning the index of the minimum vlaue od the minimum argument in the tensor

(tensor(0), tensor(0))

In [ ]:
# find the argmax
torch.argmax(x) , x.argmax() # --> returning the index of the maximum vlaue od the minimum argument in the tensor

(tensor(9), tensor(9))

# Reshaping, stacking, squeezing and unsequeezing tensors ( help us in solving shape and dimension issues ) which are very common in DL
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple Tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimension permuted (swapped) in a certain way

In [ ]:
# Lets create a tensor for performing these operations

import torch
x = torch.arange(1.,10.)
x , x.shape , x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

In [ ]:
# Add an extra dimension

#x_reshaped = x.reshape(2,9) # --> will throw an error the new dimension must be compatable with the size


x_reshaped = x.reshape(1,9)
x_reshaped = x.reshape(3,3) #
x_reshaped , x_reshaped.shape , x_reshaped.ndim

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]),
 2)

In [ ]:
# Change the view (the view of a tensor shares the same memory as the original input)

z = x.view(1,9)
z , z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing the z changes x (beacuse a view of a tensor shares the same memory as the original input )
z[:,[0,1,2]] = 4
z,x

(tensor([[4., 4., 4., 4., 5., 6., 7., 8., 9.]]),
 tensor([4., 4., 4., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensor on the top of the each other

x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[4., 4., 4., 4., 5., 6., 7., 8., 9.],
        [4., 4., 4., 4., 5., 6., 7., 8., 9.],
        [4., 4., 4., 4., 5., 6., 7., 8., 9.],
        [4., 4., 4., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - remove all single dimensions from a target tensor
x_reshaped , x_reshaped.shape

(tensor([[4., 4., 4.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
x_reshaped = x_reshaped.reshape(1,9)

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
# Now using the function of the torch.squeeeze()
x_reshaped.squeeze()

tensor([4., 4., 4., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
x_tensor = torch.rand(2,1,2,1)

In [ ]:
x_tensor , x_tensor.shape

(tensor([[[[0.9979],
           [0.0401]]],
 
 
         [[[0.0534],
           [0.1697]]]]),
 torch.Size([2, 1, 2, 1]))

In [ ]:
x_tensor.squeeze()

tensor([[0.9979, 0.0401],
        [0.0534, 0.1697]])

In [ ]:
x_tensor.squeeze().shape

torch.Size([2, 2])

In [ ]:
# Torch.unsqueeze() - add a single dimension to a target tensor at a specefic dim (dimension)

x_tensor.shape

torch.Size([2, 1, 2, 1])

In [ ]:
x_squeeze_tensor = x_tensor.squeeze()

In [ ]:
x_squeeze_tensor.shape

torch.Size([2, 2])

In [ ]:
x_unsqueeze_tensor = x_squeeze_tensor.unsqueeze(dim=0)

In [ ]:
print(x_unsqueeze_tensor.shape)
print(x_unsqueeze_tensor)

torch.Size([1, 2, 2])
tensor([[[0.9979, 0.0401],
         [0.0534, 0.1697]]])


In [ ]:
x_unsqueeze_tensor = x_squeeze_tensor.unsqueeze(dim=2)

In [ ]:
print(x_unsqueeze_tensor.shape)
print(x_unsqueeze_tensor)

torch.Size([2, 2, 1])
tensor([[[0.9979],
         [0.0401]],

        [[0.0534],
         [0.1697]]])


In [ ]:
# torch.permuted - rearranges the dimensions od a target tensor in a specefied order

x_original = torch.rand(size = (224,224,3)) # height , width , color channel

x_permutted = x_original.permute(2,0,1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permutted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0] = 123
print(x_original[0,0,0])


tensor(123.)


In [ ]:
print(x_permutted[0,0,0])

tensor(123.)


In [ ]:
x_permutted[0,0,0] = 234

In [ ]:
print(x_permutted[0,0,0])
print(x_original[0,0,0])

tensor(234.)
tensor(234.)


In [ ]:
x_permutted.shape
x_permutted.reshape(224,3,224)


tensor([[[2.3400e+02, 8.3345e-01, 1.2978e-01,  ..., 2.4266e-01,
          8.3695e-01, 8.2112e-01],
         [9.8266e-01, 2.9270e-01, 8.4049e-01,  ..., 5.0327e-01,
          8.3551e-01, 8.2765e-01],
         [8.1495e-01, 4.6772e-01, 3.1242e-01,  ..., 9.0946e-01,
          4.4688e-01, 5.1558e-01]],

        [[9.2846e-01, 2.7609e-01, 9.2324e-01,  ..., 4.8492e-01,
          9.8163e-01, 2.6029e-01],
         [6.9835e-01, 1.7929e-01, 8.3388e-01,  ..., 5.3033e-01,
          9.5638e-01, 1.6505e-01],
         [4.8186e-01, 4.3090e-01, 7.0963e-01,  ..., 2.3903e-02,
          7.9521e-01, 1.1985e-01]],

        [[8.2383e-01, 7.2790e-01, 5.9487e-02,  ..., 2.4511e-02,
          2.9500e-01, 3.4796e-01],
         [8.2337e-01, 9.7377e-01, 2.2658e-02,  ..., 8.4586e-01,
          1.1449e-01, 5.8325e-01],
         [7.9533e-01, 7.6472e-01, 2.1645e-02,  ..., 4.4600e-01,
          2.4599e-01, 9.3231e-01]],

        ...,

        [[9.5795e-01, 4.7700e-01, 2.6740e-01,  ..., 5.3080e-01,
          9.6728e-01, 1.5

In [ ]:
x_original.shape

torch.Size([224, 224, 3])

In [ ]:
print(x_original[0,0,0])

tensor(234.)


# Indexing (selecting data from tensors)

### Indexing with pytorch is same as the Numpy.

In [ ]:
import torch

In [ ]:
x = torch.arange(1,19).reshape(2,3,3)  # giving us the total of the 9 element
x , x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 torch.Size([2, 3, 3]))

In [ ]:
x[:][:][1,0]

tensor([10, 11, 12])

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
# we can also use ":" to select "all" of a target dimension
x[: , 0]

tensor([[ 1,  2,  3],
        [10, 11, 12]])

In [ ]:
# get all values of 0th and 1st deimension but only index 1 of 2nd dimension

x[:,:,1]

tensor([[ 2,  5,  8],
        [11, 14, 17]])

In [ ]:
# targeting the 18th values from the
x[1,2,2]

tensor(18)

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimesnion
x[:,1,1]

tensor([ 5, 14])

In [ ]:
# Get index 0 of the 0th and 1st dmension abd all values of 2nd dimension

x[0,0,:]

tensor([1, 2, 3])

In [ ]:
# index to get (3,6,9)

x[0,:,2]

tensor([3, 6, 9])

# PyTorch tensors & Numpy

Numpy is a popu;ar scientific python numerical computing library.
And beacuse of this, Pytovh has functionality to interact with it.

* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to Torch
import numpy as np

array = np.arange(1.0,8.0)
# tensor default data type is torch.flaot32
tensor = torch.from_numpy(array).type(torch.float32) # warning : When converting from numpy -> pytorch, pytorch reflexts numpy's default datatype of float64 unless specefied otherwise
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype

torch.float32

In [ ]:
# if we change the value of the np array this will not effect the tensor beacus we create the tensor to the new memory.

array = array + 2
array , tensor

(array([3., 4., 5., 6., 7., 8., 9.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensors to Numpy

tensor = torch.zeros(10)
np_array = tensor.numpy().astype('float64')

tensor,np_array.dtype

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), dtype('float64'))

In [ ]:
# Change the tensor , what happens to the 'np_array'

tensor = tensor + 1  # dont shares memory
tensor , np_array


(tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

# Reproducbility (Trying to take a random out of random)

In short how a neural networks learns

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**. But in torch it called a `manual seed`

 Essentially what the random seed does is "flavour" the randomness.

In [ ]:
torch.rand(3,3) # every time we run this we get the random result

tensor([[0.9272, 0.4588, 0.4474],
        [0.9878, 0.4542, 0.4745],
        [0.9721, 0.2681, 0.4592]])

In [ ]:
# Create a two random tensor
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2288, 0.5828, 0.9305, 0.9258],
        [0.0506, 0.5025, 0.6904, 0.5976],
        [0.0869, 0.3321, 0.0483, 0.2618]])
tensor([[0.7491, 0.7914, 0.3443, 0.6083],
        [0.3933, 0.8521, 0.4229, 0.9402],
        [0.9230, 0.6920, 0.0484, 0.1780]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
import torch

# Randomness with reproducibility

Random_Seed = 42
torch.manual_seed(Random_Seed)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(Random_Seed)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Getting the GPU access

#### Right now we are using the colab so simple change the runtime from cpu to gpu

#### if we want to run on the local machine then we have to do a little bit of setup in order to get the GPU access

In [ ]:
!nvidia-smi

Sat Oct  5 15:32:22 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Checking the GPU access with pytorch

In [ ]:
import torch
torch.cuda.is_available()

# cuda is nvidia programming interface that allow us to use GPUs for numerical computing

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu" # set the device to the cuda if it is available else switch to cpu
device

'cuda'

In [ ]:
# count the number of Devices
torch.cuda.device_count()

1

# Putting tensors (and more) on the GPU
### The Reason we want our tensors/models on the GPU is beacuse using a GPU results in faster computations

In [ ]:
# Create a tensor (Default on the CPU)
tensor_on_cpu = torch.rand(3,4)

# Tensor not on GPU
print(tensor_on_cpu, tensor_on_cpu.device)

tensor([[0.2328, 0.0545, 0.1804, 0.2795],
        [0.1051, 0.4210, 0.0713, 0.2797],
        [0.4976, 0.6156, 0.1531, 0.9771]]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor_on_cpu.to(device) # --> this gonna shift the tenspr_on_cpu to the target device
tensor_on_gpu

tensor([[0.2328, 0.0545, 0.1804, 0.2795],
        [0.1051, 0.4210, 0.0713, 0.2797],
        [0.4976, 0.6156, 0.1531, 0.9771]], device='cuda:0')

# Moving tensors back to the CPU

In [ ]:
# Now will see the tensor device error issues.
tensor_on_gpu.numpy()  # --> numpy doesn't works on the GPU it works on the CPU

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([[0.23275101, 0.05451506, 0.18037581, 0.279518  ],
       [0.10506815, 0.4209569 , 0.07125467, 0.2796842 ],
       [0.49758953, 0.61557263, 0.153067  , 0.9771342 ]], dtype=float32)